# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
