# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20170806_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=0, on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
    ]
